# Generated by Django 5.0.2 on 2024-02-21 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BreakTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_stamp", models.DateTimeField()),
                ("out_stamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="EndTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StartTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailyTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "breaks",
                    models.ManyToManyField(
                        blank=True, null=True, to="time_backend.breaktime"
                    ),
                ),
                (
                    "end_time",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_backend.endtime",
                    ),
                ),
                (
                    "start_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_backend.starttime",
                    ),
                ),
            ],
        ),
    ]
