# Generated by Django 5.0.1 on 2024-01-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClockedTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.IntegerField()),
                ("minutes", models.IntegerField()),
                ("clock_type", models.CharField(default="IN", max_length=50)),
                ("created_on", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("payed_taxes", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "platform",
                    models.TextField(
                        choices=[
                            ("Corepoint", "Corepoint"),
                            ("Envisirad", "Envisirad"),
                            ("Ssms", "Ssms"),
                        ],
                        default="Envisirad",
                    ),
                ),
                ("created_on", models.DateField(auto_now_add=True)),
                ("severity", models.IntegerField()),
            ],
        ),
    ]
