# Generated by Django 5.0.1 on 2024-01-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work_portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="remind_me",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
