# Generated by Django 4.1.5 on 2023-01-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='msg',
            field=models.CharField(blank=True, default='msg', max_length=100, null=True),
        ),
    ]
