// ALERT DISPATCH STATES
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// Category Dispatch States
export const LOAD_CAT_SUCCESS = 'LOAD_CAT_SUCCESS'
export const LOAD_CAT_FAIL = 'LOAD_CAT_FAIL'
export const LOAD_CATS_SUCCESS = 'LOAD_CATS_SUCCESS'
export const LOAD_CATS_FAIL = 'LOAD_CATS_FAIL'
export const UPLOAD_CAT_SUCCESS = 'UPLOAD_CAT_SUCCESS'
export const UPLOAD_CAT_FAIL = 'UPLOAD_CAT_FAIL'

// TimeStamp Dispatch States
export const LOAD_TS_SUCCESS = 'LOAD_TS_SUCCESS'
export const LOAD_TS_FAIL = 'LOAD_TS_FAIL'
export const LOAD_TSS_SUCCESS = 'LOAD_TSS_SUCCESS'
export const LOAD_TSS_FAIL = 'LOAD_TSS_FAIL'
export const REMOVE_TS_SUCCESS = 'REMOVE_TS_SUCCESS'
export const UPLOAD_TS_SUCCESS = 'UPLOAD_TS_SUCCESS'
export const REMOVE_TS_FAIL = 'REMOVE_TS_FAIL'
export const UPLOAD_TS_FAIL = 'UPLOAD_TS_FAIL'
export const LOAD_TS_BY_CAT_SUCCESS = 'LOAD_TS_BY_CAT_SUCCESS'
export const LOAD_TS_BY_CAT_FAIL = 'LOAD_TS_BY_CAT_FAIL'

